name= "hono-with-react"
type = "javascript"
workers_dev = true

compatibility_date = "2022-03-01"

[site]
bucket = "./public"
entry-point = "./"

[build]
command = "yarn run build"

[build.upload]
format = "service-worker"
